#!/bin/bash

 ###
#Sitio donde puede ver y estudiar la documentación de git commit
#de donde se bas este script de reglas pre-commit para realizar push
#"https://www.conventionalcommits.org/en/v1.0.0/" 
#"https://midu.dev/buenas-practicas-escribir-commits-git/"
 ###
# Verifica si se ha pasado el archivo de mensaje de commit
if [ -f "$1" ]; then
    # Obtener el mensaje de commit desde el archivo de mensaje
    commit_msg=$(head -n 1 "$1")

    # Verificar que el mensaje comience con "fix:", "feat:", "docs:", "style:", "refactor:", o "chore:"
    if [[ ! "$commit_msg" =~ ^(fix:|feat:|docs:|style:|refactor:|chore:|perf:|ci:|test:) ]]; then
        # Si no cumple, muestra un error y cancela el commit
        echo "Error: El mensaje de commit debe comenzar con uno de los siguientes prefijos: 'fix:', 'feat:', 'docs:', 'style:', 'refactor:', 'chore:'"
        echo "Por favor, use uno de estos prefijos para describir su cambio."
        exit 1
    fi

      # Verificar que el mensaje tenga un máximo de 50 caracteres
    if [ ${#commit_msg} -gt 60 ]; then
        echo "Error: El mensaje de commit no debe exceder los 60 caracteres."
        echo "Actual: ${#commit_msg} caracteres."
        exit 1
    fi

     # Verificar que el mensaje no termine con un punto
    if [[ "$commit_msg" =~ \.$ ]]; then
        echo "Error: El mensaje de commit no debe terminar con un punto."
        exit 1
    fi
fi
